# -*- coding: utf-8 -*-
"""Shapeai_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKBvFcdSQBijdcmIHyM-aXPjMnnzigvK
"""

import requests,sys
 
#import os
from datetime import datetime

f = open('output.txt','w')
sys.stdout = f

api_key = '77efa455a78184db3b13abfe4b329d50'
location = input("Enter the city name: ")

"""# New Section"""

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
wind_spd = api_data['wind']['speed']

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')